plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Admin\\OneDrive\\Documents\\yos\\MD_Network\\stitch-wifi-cms\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Admin\\OneDrive\\Documents\\yos\\MD_Network\\stitch-wifi-cms"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]