[build]
base = "stitch-wifi-cms"
command = "npm run build"
publish = "dist"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]
